name: Saludo en push

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Saludar
        run: echo "Hola, GitHub Actions"
